import { Router } from "express";
import { eq, and, ilike, desc, sql } from "drizzle-orm";
import { db, projects, projectVersions } from "@workspace/db";
import {
  CreateProjectBody,
  UpdateProjectBody,
  ExportProjectBody,
} from "@workspace/api-zod";
import { requireAuth, type AuthenticatedRequest } from "../middlewares/auth";
import { parseId } from "../lib/parseId";
import JSZip from "jszip";
import { randomUUID } from "node:crypto";

const router = Router();

function xmlEscape(s: unknown): string {
  return String(s ?? "").replace(/[&<>"']/g, (c) =>
    c === "&" ? "&amp;" : c === "<" ? "&lt;" : c === ">" ? "&gt;" : c === '"' ? "&quot;" : "&apos;"
  );
}

/**
 * EXPERIMENTAL: best-effort reconstruction of an Archer ".archer" package
 * (a zip archive containing an XML object-definition manifest).
 *
 * Archer's real package format is proprietary and normally only produced by
 * Archer's own Package Manager ("Export Package"); there is no public spec
 * for it. This is a best-effort approximation based on the object shapes
 * Archer's Package Manager exposes on export (Application > Levels > Fields,
 * ValuesLists, Workflow). It is NOT guaranteed to pass Archer's package
 * import validation — treat it as a gamble, with the Build Guide export as
 * the reliable fallback if import fails.
 */
async function buildExperimentalArcherPackage(
  projectName: string,
  content: Record<string, unknown> | null
): Promise<Buffer> {
  const asObjectArray = (v: unknown): Record<string, any>[] =>
    Array.isArray(v) ? v.filter((x): x is Record<string, any> => x !== null && typeof x === "object") : [];

  const impl = (content ?? {}) as Record<string, unknown>;
  const modules = asObjectArray(impl.modules);
  const fields = asObjectArray(impl.fields);
  const valueLists = asObjectArray(impl.valueLists);
  const workflow = (impl.workflow && typeof impl.workflow === "object" ? impl.workflow : {}) as any;
  const stages = Array.isArray(workflow.stages) ? workflow.stages : [];

  const appGuid = randomUUID();

  const levelsXml = modules.length
    ? modules
        .map(
          (m) =>
            `      <Level guid="${randomUUID()}" name="${xmlEscape(m.name ?? "Level")}">${
              m.description ? `<Description>${xmlEscape(m.description)}</Description>` : ""
            }</Level>`
        )
        .join("\n")
    : `      <Level guid="${randomUUID()}" name="${xmlEscape(projectName)}"/>`;

  const fieldsXml = fields
    .map(
      (f) =>
        `      <Field guid="${randomUUID()}" name="${xmlEscape(f.name ?? "Field")}" type="${xmlEscape(
          f.type ?? "Text"
        )}" required="${f.required ? "true" : "false"}"${
          f.module ? ` level="${xmlEscape(f.module)}"` : ""
        }/>`
    )
    .join("\n");

  const valueListsXml = valueLists
    .map((vl) => {
      const values: unknown[] = Array.isArray(vl.values) ? vl.values : Array.isArray(vl.options) ? vl.options : [];
      const valuesXml = values
        .map((v) => `        <Value guid="${randomUUID()}">${xmlEscape(typeof v === "string" ? v : (v as any)?.name)}</Value>`)
        .join("\n");
      return `      <ValuesList guid="${randomUUID()}" name="${xmlEscape(vl.name ?? "Values List")}">\n${valuesXml}\n      </ValuesList>`;
    })
    .join("\n");

  const workflowXml = stages.length
    ? `      <Workflow name="${xmlEscape(workflow.name ?? `${projectName} Workflow`)}">\n${stages
        .map(
          (s: any, i: number) =>
            `        <Stage guid="${randomUUID()}" order="${i + 1}" name="${xmlEscape(typeof s === "string" ? s : s?.name ?? `Stage ${i + 1}`)}"/>`
        )
        .join("\n")}\n      </Workflow>`
    : "";

  const manifestXml = `<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="urn:archerpilot:experimental-package" generator="ArcherPilot AI" experimental="true">
  <Application guid="${appGuid}" name="${xmlEscape(projectName)}">
${impl.businessOverview ? `    <Description>${xmlEscape(impl.businessOverview)}</Description>\n` : ""}    <Levels>
${levelsXml}
    </Levels>
    <Fields>
${fieldsXml}
    </Fields>
    <ValuesLists>
${valueListsXml}
    </ValuesLists>
${workflowXml}
  </Application>
</Package>
`;

  const readme = `ArcherPilot AI — Experimental Archer Package
================================================

This .archer file is an EXPERIMENTAL, UNOFFICIAL reconstruction of Archer's
package format. It was generated by ArcherPilot AI, not by Archer's own
Package Manager, because Archer's real package format is proprietary and
undocumented publicly.

It may fail import validation in Archer's Package Manager
(Manage > Packages / System > Import/Export, depending on your build).

If import fails or produces a partial/broken application:
  -> Use the "Download Build Guide" export instead. It gives you the exact
     same design as a step-by-step manual checklist for Archer's
     Application Builder wizard, which is guaranteed to work.

Contents:
  - manifest.xml   Application/Levels/Fields/ValuesLists/Workflow definition
`;

  const zip = new JSZip();
  zip.file("manifest.xml", manifestXml);
  zip.file("README.txt", readme);
  return zip.generateAsync({ type: "nodebuffer", compression: "DEFLATE" });
}

/**
 * Build a step-by-step manual build guide, ordered to match RSA Archer's
 * Application Builder wizard exactly, so a human can click through it in
 * ~15-20 minutes instead of designing the app from scratch. This is the
 * reliable fallback for Archer versions (like 6.15) whose REST API does not
 * expose creation endpoints for application structure.
 */
function buildApplicationBuilderGuide(projectName: string, content: Record<string, unknown> | null): string {
  // Only keep plain-object, non-null entries; anything malformed (null, string,
  // number) is silently dropped rather than throwing mid-export.
  const asObjectArray = (v: unknown): Record<string, any>[] =>
    Array.isArray(v) ? v.filter((x): x is Record<string, any> => x !== null && typeof x === "object") : [];

  const impl = (content ?? {}) as Record<string, unknown>;
  const modules = asObjectArray(impl.modules);
  const fields = asObjectArray(impl.fields);
  const valueLists = asObjectArray(impl.valueLists);
  const crossRefs = asObjectArray(impl.crossReferences);
  const workflow = (impl.workflow && typeof impl.workflow === "object" ? impl.workflow : {}) as any;
  const permissions = asObjectArray(impl.recordPermissions);
  const notifications = asObjectArray(impl.notifications);
  const reports = asObjectArray(impl.reports);
  const dashboards = asObjectArray(impl.dashboards);

  const md: string[] = [];
  const h = (n: number, t: string) => md.push(`${"#".repeat(n)} ${t}`, "");
  const li = (t: string) => md.push(`- ${t}`);

  h(1, `${projectName} — Archer Application Builder Guide`);
  md.push(
    "> Follow these steps in order inside **Archer → Manage → Application Builder**.",
    "> Each section matches a screen in the Application Builder wizard, so you can build this application manually in one pass.",
    ""
  );

  if (impl.businessOverview) {
    h(2, "Business Overview");
    md.push(String(impl.businessOverview), "");
  }
  if (Array.isArray(impl.useCases) && impl.useCases.length) {
    h(2, "Use Cases");
    (impl.useCases as string[]).forEach((uc) => li(uc));
    md.push("");
  }

  h(2, "Step 1 — Create the Application");
  md.push(
    "In **Application Builder → Manage Applications → Add New → Application**, enter:",
    ""
  );
  li(`**Name:** ${projectName}`);
  if (impl.applicationStructure && typeof impl.applicationStructure === "object") {
    for (const [k, v] of Object.entries(impl.applicationStructure as Record<string, unknown>)) {
      if (v != null && typeof v !== "object") li(`**${k}:** ${v}`);
    }
  }
  md.push("");

  if (modules.length) {
    h(2, "Step 2 — Create Levels / Modules");
    md.push("For each level below, use **Manage → Levels → Add New Level**:", "");
    modules.forEach((m, i) => {
      md.push(`${i + 1}. **${m.name ?? `Level ${i + 1}`}**${m.description ? ` — ${m.description}` : ""}`);
    });
    md.push("");
  }

  if (valueLists.length) {
    h(2, "Step 3 — Create Value Lists");
    md.push("In **Manage → Values Lists → Add New**, create these before adding fields that reference them:", "");
    valueLists.forEach((vl) => {
      md.push(`**${vl.name ?? "Unnamed Value List"}**`);
      const values = Array.isArray(vl.values) ? vl.values : Array.isArray(vl.options) ? vl.options : [];
      values.forEach((v: any) => li(typeof v === "string" ? v : v?.name ?? JSON.stringify(v)));
      md.push("");
    });
  }

  if (fields.length) {
    h(2, "Step 4 — Add Fields");
    md.push("In the target level's **Manage Fields** screen, add these fields in order (this also determines the Layout tab order):", "");
    md.push("| # | Field Name | Type | Value List | Required |", "|---|---|---|---|---|");
    fields.forEach((f, i) => {
      md.push(
        `| ${i + 1} | ${f.name ?? "—"} | ${f.type ?? "Text"} | ${f.valueList ?? f.valuesList ?? "—"} | ${f.required ? "Yes" : "No"} |`
      );
    });
    md.push("");
  }

  if (crossRefs.length) {
    h(2, "Step 5 — Cross-References");
    md.push("Both target applications must already exist before adding these. In **Manage Fields → Add New → Cross-Reference**:", "");
    crossRefs.forEach((cr) => {
      li(`**${cr.name ?? "Cross-Reference"}** → target application: ${cr.targetApplication ?? cr.target ?? "—"}${cr.description ? ` (${cr.description})` : ""}`);
    });
    md.push("");
  }

  if (workflow && (workflow.stages || workflow.name)) {
    h(2, "Step 6 — Workflow (Workflow Manager)");
    md.push("Open **Manage → Workflow → Create New Workflow** and add these stages in order:", "");
    const stages = Array.isArray(workflow.stages) ? workflow.stages : [];
    stages.forEach((s: any, i: number) => {
      md.push(`${i + 1}. **${typeof s === "string" ? s : s.name ?? `Stage ${i + 1}`}**${typeof s === "object" && s.description ? ` — ${s.description}` : ""}`);
    });
    md.push("", "Attach the workflow to the application under **Application Properties → Workflow**.", "");
  }

  if (permissions.length) {
    h(2, "Step 7 — Record Permissions");
    md.push("In **Manage → Access Roles**, create/assign these roles:", "");
    permissions.forEach((p) => {
      li(`**${p.group ?? p.role ?? "Group"}** — ${p.access ?? p.permissions ?? p.description ?? "Access as specified"}`);
    });
    md.push("");
  }

  if (notifications.length) {
    h(2, "Step 8 — Notifications");
    md.push("In **Manage → Notifications → Add New**, create these rules:", "");
    notifications.forEach((n) => {
      li(`**${n.name ?? "Notification"}** — trigger: ${n.trigger ?? n.event ?? "—"}, recipients: ${n.recipients ?? "—"}`);
    });
    md.push("");
  }

  if (reports.length) {
    h(2, "Step 9 — Reports");
    reports.forEach((r) => li(`**${r.name ?? "Report"}**${r.description ? ` — ${r.description}` : ""}`));
    md.push("");
  }

  if (dashboards.length) {
    h(2, "Step 10 — Dashboards");
    dashboards.forEach((d) => li(`**${d.name ?? "Dashboard"}**${d.description ? ` — ${d.description}` : ""}`));
    md.push("");
  }

  md.push("---", `_Generated by ArcherPilot AI — designed to be built manually in Archer Application Builder, no trace of AI in the final application._`);
  return md.join("\n");
}

// GET /projects
router.get("/projects", requireAuth, async (req, res) => {
  const r = req as AuthenticatedRequest;
  const { status, search } = req.query as { status?: string; search?: string };

  try {
    const conditions = [eq(projects.userId, r.userId)];
    if (status) conditions.push(eq(projects.status, status));
    if (search) conditions.push(ilike(projects.name, `%${search}%`));

    const rows = await db
      .select({
        id: projects.id,
        userId: projects.userId,
        name: projects.name,
        description: projects.description,
        status: projects.status,
        prompt: projects.prompt,
        content: projects.content,
        createdAt: projects.createdAt,
        updatedAt: projects.updatedAt,
        versionCount: sql<number>`(select count(*) from project_versions where project_id = ${projects.id})::int`,
      })
      .from(projects)
      .where(and(...conditions))
      .orderBy(desc(projects.updatedAt));

    res.json(rows);
  } catch (err) {
    req.log.error(err);
    res.status(500).json({ error: "Failed to list projects" });
  }
});

// POST /projects
router.post("/projects", requireAuth, async (req, res) => {
  const r = req as AuthenticatedRequest;
  const parsed = CreateProjectBody.safeParse(req.body);
  if (!parsed.success) {
    res.status(400).json({ error: parsed.error.message });
    return;
  }

  try {
    const [project] = await db
      .insert(projects)
      .values({ ...parsed.data, userId: r.userId })
      .returning();

    res.status(201).json({ ...project, versionCount: 0 });
  } catch (err) {
    req.log.error(err);
    res.status(500).json({ error: "Failed to create project" });
  }
});

// GET /projects/:id
router.get("/projects/:id", requireAuth, async (req, res) => {
  const r = req as AuthenticatedRequest;
  const id = parseId(req.params.id, res);
  if (id === null) return;

  try {
    const [row] = await db
      .select({
        id: projects.id,
        userId: projects.userId,
        name: projects.name,
        description: projects.description,
        status: projects.status,
        prompt: projects.prompt,
        content: projects.content,
        createdAt: projects.createdAt,
        updatedAt: projects.updatedAt,
        versionCount: sql<number>`(select count(*) from project_versions where project_id = ${projects.id})::int`,
      })
      .from(projects)
      .where(and(eq(projects.id, id), eq(projects.userId, r.userId)));

    if (!row) {
      res.status(404).json({ error: "Project not found" });
      return;
    }
    res.json(row);
  } catch (err) {
    req.log.error(err);
    res.status(500).json({ error: "Failed to get project" });
  }
});

// PUT /projects/:id
router.put("/projects/:id", requireAuth, async (req, res) => {
  const r = req as AuthenticatedRequest;
  const id = parseId(req.params.id, res);
  if (id === null) return;
  const parsed = UpdateProjectBody.safeParse(req.body);
  if (!parsed.success) {
    res.status(400).json({ error: parsed.error.message });
    return;
  }

  try {
    const existing = await db
      .select()
      .from(projects)
      .where(and(eq(projects.id, id), eq(projects.userId, r.userId)));
    if (!existing.length) {
      res.status(404).json({ error: "Project not found" });
      return;
    }

    // Save version before updating
    const currentVersionCount = await db
      .select({ count: sql<number>`count(*)::int` })
      .from(projectVersions)
      .where(eq(projectVersions.projectId, id));

    if (parsed.data.content && existing[0].content) {
      await db.insert(projectVersions).values({
        projectId: id,
        versionNumber: (currentVersionCount[0]?.count ?? 0) + 1,
        content: existing[0].content as Record<string, unknown>,
      });
    }

    const [updated] = await db
      .update(projects)
      .set({ ...parsed.data, updatedAt: new Date() })
      .where(and(eq(projects.id, id), eq(projects.userId, r.userId)))
      .returning();

    const [{ vc }] = await db
      .select({ vc: sql<number>`count(*)::int` })
      .from(projectVersions)
      .where(eq(projectVersions.projectId, id));

    res.json({ ...updated, versionCount: vc });
  } catch (err) {
    req.log.error(err);
    res.status(500).json({ error: "Failed to update project" });
  }
});

// DELETE /projects/:id
router.delete("/projects/:id", requireAuth, async (req, res) => {
  const r = req as AuthenticatedRequest;
  const id = parseId(req.params.id, res);
  if (id === null) return;

  try {
    const deleted = await db
      .delete(projects)
      .where(and(eq(projects.id, id), eq(projects.userId, r.userId)))
      .returning();

    if (!deleted.length) {
      res.status(404).json({ error: "Project not found" });
      return;
    }
    res.status(204).send();
  } catch (err) {
    req.log.error(err);
    res.status(500).json({ error: "Failed to delete project" });
  }
});

// POST /projects/:id/duplicate
router.post("/projects/:id/duplicate", requireAuth, async (req, res) => {
  const r = req as AuthenticatedRequest;
  const id = parseId(req.params.id, res);
  if (id === null) return;

  try {
    const [original] = await db
      .select()
      .from(projects)
      .where(and(eq(projects.id, id), eq(projects.userId, r.userId)));

    if (!original) {
      res.status(404).json({ error: "Project not found" });
      return;
    }

    const [copy] = await db
      .insert(projects)
      .values({
        userId: r.userId,
        name: `${original.name} (Copy)`,
        description: original.description,
        status: "draft",
        prompt: original.prompt,
        content: original.content as Record<string, unknown>,
      })
      .returning();

    res.status(201).json({ ...copy, versionCount: 0 });
  } catch (err) {
    req.log.error(err);
    res.status(500).json({ error: "Failed to duplicate project" });
  }
});

// GET /projects/:id/versions
router.get("/projects/:id/versions", requireAuth, async (req, res) => {
  const r = req as AuthenticatedRequest;
  const id = parseId(req.params.id, res);
  if (id === null) return;

  try {
    const owner = await db
      .select({ id: projects.id })
      .from(projects)
      .where(and(eq(projects.id, id), eq(projects.userId, r.userId)));
    if (!owner.length) {
      res.status(404).json({ error: "Project not found" });
      return;
    }

    const versions = await db
      .select()
      .from(projectVersions)
      .where(eq(projectVersions.projectId, id))
      .orderBy(desc(projectVersions.versionNumber));

    res.json(versions);
  } catch (err) {
    req.log.error(err);
    res.status(500).json({ error: "Failed to list versions" });
  }
});

// POST /projects/:id/export
router.post("/projects/:id/export", requireAuth, async (req, res) => {
  const r = req as AuthenticatedRequest;
  const id = parseId(req.params.id, res);
  if (id === null) return;
  const parsed = ExportProjectBody.safeParse(req.body);
  if (!parsed.success) {
    res.status(400).json({ error: parsed.error.message });
    return;
  }

  try {
    const [project] = await db
      .select()
      .from(projects)
      .where(and(eq(projects.id, id), eq(projects.userId, r.userId)));

    if (!project) {
      res.status(404).json({ error: "Project not found" });
      return;
    }

    const { format } = parsed.data;
    const content = project.content as Record<string, unknown> | null;

    let exportContent = "";
    let filename = `${project.name.replace(/\s+/g, "_")}`;
    let mimeType = "application/octet-stream";

    switch (format) {
      case "json":
        exportContent = JSON.stringify(content, null, 2);
        filename += ".json";
        mimeType = "application/json";
        break;
      case "archer-package": {
        const zipBuffer = await buildExperimentalArcherPackage(project.name, content);
        res.json({
          format,
          filename: `${filename}.archer`,
          content: zipBuffer.toString("base64"),
          mimeType: "application/zip",
          experimental: true,
          warning:
            "This is an experimental, unofficial reconstruction of Archer's package format. " +
            "It is NOT generated by Archer itself and may fail Archer's Package Manager import validation. " +
            "If import fails, use the Build Guide export to create the application manually instead.",
        });
        return;
      }
      case "markdown": {
        exportContent = buildApplicationBuilderGuide(project.name, content);
        filename += "_build_guide.md";
        mimeType = "text/markdown";
        break;
      }
      default:
        exportContent = JSON.stringify(content, null, 2);
        filename += ".json";
        mimeType = "application/json";
    }

    res.json({
      format,
      filename,
      content: Buffer.from(exportContent).toString("base64"),
      mimeType,
    });
  } catch (err) {
    req.log.error(err);
    res.status(500).json({ error: "Failed to export project" });
  }
});

export default router;
